FROM grafana/grafana:11.2.2

COPY infra/observability/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY infra/observability/grafana/provisioning/datasources/prometheus.ecs.yml /etc/grafana/provisioning/datasources/prometheus.yml
COPY infra/observability/grafana/dashboards /var/lib/grafana/dashboards

ENV GF_SECURITY_ADMIN_USER=admin \
    GF_USERS_ALLOW_SIGN_UP=false \
    GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/ \
    GF_SERVER_SERVE_FROM_SUB_PATH=true

EXPOSE 3000
